mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

# ——首包与并发优化——
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
profile:
  store-selected: true

# ——嗅探（Mihomo）——
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  force-domain:
    - +.netflix.com
    - +.youtube.com
    - +.googlevideo.com
  skip-domain:
    - +.local
    - +.lan

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  respect-rules: true

  # 冷启动用直连上游（快、避免环依赖）
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # 国外域名 → 经 Proxy 出站的 DoH
  nameserver-policy:
    "geosite:cn":
      - 223.5.5.5
      - 119.29.29.29
    "geosite:geolocation-!cn":
      - https://1.1.1.1/dns-query#Proxy
      - https://8.8.8.8/dns-query#Proxy

  fallback:
    - https://1.1.1.1/dns-query#Proxy
    - https://8.8.8.8/dns-query#Proxy
    - tls://1.1.1.1:853#Proxy
    - tls://8.8.8.8:853#Proxy
  fallback-filter:
    geoip: true
    geoip-code: CN
    ip-cidr:
      - 240.0.0.0/4

  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "localhost"
    - "connectivitycheck.gstatic.com"
    - "msftconnecttest.com"
    - "msftncsi.com"
    - "time.windows.com"
    - "time.apple.com"
    - "pool.ntp.org"
    - "ntp.ntsc.ac.cn"
    - "router.asus.com"
    - "miwifi.com"
    - "dns.alidns.com"
    - "resolver1.opendns.com"
    - "stun.l.google.com"
    - "download.windowsupdate.com"

# ——节点列表——
proxies:
  - name: "美国01"
    type: vless
    server: jiangniao.jiangniao44.top
    port: 49545
    uuid: 8f7953fa-5ed6-4690-aaf1-f0c3da17d7a0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "4f-7xFlaZty0ZhYib5NHTvnxt22m7LaRUkSJbthWMAM"
      short-id: "5247b7"
      spider-x: "/"

  - name: "美国02"
    type: vless
    server: jiang.jiangniao.de
    port: 32313
    uuid: 741278f0-e49c-4aa3-9f00-7933987534f0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "KL9NC2B3k5E7IfghGcA9ocF-7MdvuAgdPR7Zj4ljSlI"
      short-id: "954ae509e86e10"
      spider-x: "/"

  - name: "美国03"
    type: vless
    server: jiang.jiangniao.de
    port: 33901
    uuid: 6649a959-da30-46b6-a282-93f3cc91019a
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "7pEGJXrnTqrq4BvWCod1TLgCu99W1RENDrvinvdRaW4"
      short-id: "8a7cc0e4e9"
      spider-x: "/"

  - name: "日本01"
    type: vless
    server: gomami.jiangniao.de
    port: 20370
    uuid: 90483522-652b-47a8-8e25-9e6f15e00f72
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "6ahd-83CxsUfdvw6uiTbVGYWcjFOxDXOtTOrjzFde1A"
      short-id: "4d2e2df44042"
      spider-x: "/"

  - name: "日本02"
    type: vless
    server: jiang1314.jiangniao44.top
    port: 17069
    uuid: c2766b94-fd4b-42ae-83c9-5fb33bf4e040
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "afrH0HGqS4Z4LZEOTz6MvCLrh-py7MdW60dhQmkZV2A"
      short-id: "8fd8ce6c00813c"
      spider-x: "/"

  - name: "日本03"
    type: vless
    server: gomami.jiangniao.de
    port: 57460
    uuid: a069cca6-d6e1-423b-9901-5ebe12766253
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "sOX026sVJ2dAQqG2B3YCmspTcx5oB58ILxX_zqyPK10"
      short-id: "37b312"
      spider-x: "/"

  - name: "日本04"
    type: vless
    server: green.jiangniao.de
    port: 51790
    uuid: 1b69afb7-9f0a-4e6c-9a4b-1fcf7621b0be
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "XJa0ZYOvtfwRz7aF8GprVrnEjc4S1rokGFhc-tI1YFk"
      short-id: "02c40852"
      spider-x: "/"

  - name: "日本05"
    type: vless
    server: gomami.jiangniao.de
    port: 17879
    uuid: 40ee69a1-c20d-46d4-ad40-b8aeb0a250f8
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "o0_ylMwYlfZQYSCSe14pbn1sXifirIzpXas0MTrztg8"
      short-id: "48"
      spider-x: "/"

  - name: "新加坡01"
    type: vless
    server: rfc.jiangniao.de
    port: 50821
    uuid: 6227227f-52ab-4695-8177-62855023cc70
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "fU7DWzwdZhRezE1rNnCLGQkvUjhrDKJ9fO9lTzf9MRs"
      short-id: "4a"
      spider-x: "/"

  - name: "香港01"
    type: vless
    server: niao.jiangniao44.top
    port: 56079
    uuid: d2e6f717-0cdf-44f5-81e1-ad7f969ed903
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "8txY8epXE1T3O7H6-NVxleE_-J4dCVf4HSP6zdsx4TI"
      short-id: "8332"
      spider-x: "/"

  - name: "香港02"
    type: vless
    server: cnf.jiangniao.de
    port: 14339
    uuid: 305b46c8-62c5-4a5f-8eca-49696504b4c9
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "mFLxuM5neHOj_JiAaSXzKhQHNBjJOdMrcvi0nBZvoHg"
      short-id: "ff6c1c7939"
      spider-x: "/"

  - name: "香港03"
    type: vless
    server: rfc.jiangniao.de
    port: 14967
    uuid: 5f7e69bb-dd40-4b60-8984-5a1f1730091b
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "d1dzvm7d9JN2JunFIU0-cXH6ooS6VT-fUi_Z0G2Tfys"
      short-id: "ce9c32d59c9c8189"
      spider-x: "/"

  - name: "香港03（RFC）"
    type: vless
    server: rfc.jiangniao.de
    port: 47902
    uuid: e1399ad8-3e06-47f4-957e-9b81592210ad
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "YL6YPweNQPotVbSO9tj3pnJc_ZyAq43WBIHiSzJNV3U"
      short-id: "91a90ab02da3d300"
      spider-x: "/"

  - name: "香港04"
    type: vless
    server: rfc.jiangniao.de
    port: 49624
    uuid: 6245f873-c14d-4cc9-895c-5e1816a8debb
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "qfH78UdGFMqCFfdPpHgHI5szzu2KXrVpxoyG12lZono"
      short-id: "a4"
      spider-x: "/"

  - name: "香港05"
    type: vless
    server: rfc.jiangniao.de
    port: 27277
    uuid: 4564fd83-b46f-4781-ba74-fd2b6a29875c
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "J2b48DFltcG4Eg4ZUlzoi76Mvx20U_kLhKnUyFZKXyA"
      short-id: "286927"
      spider-x: "/"

  - name: "香港X"
    type: vless
    server: rfc.jiangniao.de
    port: 47372
    uuid: 2f18157f-361e-4da9-a43d-abea314f82a8
    network: tcp
    tls: true
    udp: false
    flow: "xtls-rprx-vision"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "1OGj_Ab2uxPN0HMe29mgjuXeGJqqPZCuUSUWVU1h4mE"
      short-id: "a48c6562f9f96d35"
      spider-x: "/"

  - name: "印度01"
    type: vless
    server: rfc.jiangniao.de
    port: 16038
    uuid: ad898dc0-5173-4d84-a495-92adbee22bde
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "Wi_dye6vy6jr4iEBPHJKvBCf-bXflSlp_AI84tuQfzE"
      short-id: "7c485f0d"
      spider-x: "/"

  - name: "土耳其01"
    type: vless
    server: jiang.jiangniao.de
    port: 27519
    uuid: 34c19ca4-2f3d-45e0-aa58-24846d80a7fe
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "kAx8PXXiu9rj_axNsOFT0XwKo2Wg4iaJcJ7AzhYOMyM"
      short-id: "7388efc99b645c49"
      spider-x: "/"

  - name: "墨西哥01"
    type: vless
    server: jiang.jiangniao.de
    port: 42025
    uuid: bed8750e-36e0-425d-ae14-48d5b70cedd9
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "6baH2z3cSHXyNF-y60uOu15VRrHIA1s0w-c7DXvNLG4"
      short-id: "e5d928499470"
      spider-x: "/"

  - name: "墨西哥02"
    type: vless
    server: jiang.jiangniao.de
    port: 50682
    uuid: 41fe730f-127b-4c27-81ef-7e2a240b5e2e
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "zIIPhsd4pP9omVPxtUbusaJq9UcY7artFMY70MLQiWg"
      short-id: "6f110ee0d9fd"
      spider-x: "/"

  - name: "墨西哥03"
    type: vless
    server: jiang.jiangniao.de
    port: 41236
    uuid: 1a16fad3-3182-445f-b27b-db018e4e5746
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "lDSUkgWuvxEQ1RzMbuwGCqdX7bn3uDetAYJmP4HGhXA"
      short-id: "c5475819"
      spider-x: "/"

  - name: "墨西哥04"
    type: vless
    server: jiang.jiangniao.de
    port: 21699
    uuid: 6e822f5f-4d65-4d7a-ab9b-44b2286c205d
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "dDrx6x-HWghQs3x_s5bVW8VICdhhACVYTThlHScWlyI"
      short-id: "9d3ec8"
      spider-x: "/"

  - name: "墨西哥05"
    type: vless
    server: jiang.jiangniao.de
    port: 12852
    uuid: e96ab706-0aa6-4ff6-820a-6f3549dd3319
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "uInXYi-6Bd6C061wSjWpFZTaE8Hd1fS3MBsU57geT0I"
      short-id: "28fcba0ec25e"
      spider-x: "/"

  - name: "墨西哥06"
    type: vless
    server: jiang.jiangniao.de
    port: 44779
    uuid: 6ae3ada1-49c6-48ab-8cd3-53b63ae2e9f1
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "l9y_VNGHADyIsENlPgZxkhGPy8u3YzIJKC73GD8fuS4"
      short-id: "6eb946ae72a615"
      spider-x: "/"

  - name: "尼日利亚01"
    type: vless
    server: jiang.jiangniao.de
    port: 19253
    uuid: fad9f8a7-13f3-4d42-823a-b7e9f6aff4f5
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "LKZqdbkcQcCmHqSOIlPA8_5sXuWs_GKJJt3S5WW5Jko"
      short-id: "4a9c954f51a83119"
      spider-x: "/"

  - name: "尼日利亚02"
    type: vless
    server: nl.jiangniao.de
    port: 20041
    uuid: 9edaf9dc-ad9f-45dd-a9a6-0607b319ce95
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "iuzReYVzAP_fsSv_AZZo-kkUx4HWg-u0GjphpiNzC2w"
      short-id: "199eb1a29e"
      spider-x: "/"

  - name: "荷兰01"
    type: vless
    server: nl.jiangniao.de
    port: 30383
    uuid: 49a84f88-9c07-4d87-bbe8-066f720cc98b
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "SQzMdT0zNEo_hoEjkgwYxZkIQ7OKE1SCz1lRiwPpmwY"
      short-id: "84"
      spider-x: "/"


  - name: "德国01"
    type: vless
    server: snapstack.jiangniao.de
    port: 11873
    uuid: 1d9dae7c-db5b-4d78-b4cc-2933459713cb
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "zz63GUGkBDMUvZNzEY6ugD6XYuNT0TIe-NefzNhqEhw"
      short-id: "e4"
      spider-x: "/"

  - name: "美国家宽01"
    type: vless
    server: jiang.jiangniao.de
    port: 35111
    uuid: 2108bb8f-96e3-4cb6-885e-9c7e3d769f90
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "CwOikz2Soyfs5YVZBuDMdKRjZ7IfAPWQr_prrvh38DM"
      short-id: "30e09630b2b7af"
      spider-x: "/"

  - name: "德国家宽01"
    type: vless
    server: nl.jiangniao.de
    port: 39174
    uuid: b9b4090c-251e-4d3c-84bf-8e4ba26831dc
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "V3C6W3hKfwca-5Hi0MHCZSnkF-a9B45UjxqoklhWHmk"
      short-id: "b6"
      spider-x: "/"

  - name: "英国01"
    type: vless
    server: nl.jiangniao.de
    port: 13354
    uuid: b66d86d5-a62c-4446-837a-d443a8aa23ff
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "qI2y3py3S4HEbR0kMSN2VypO3Z6R4LHVJY8zNa35wEU"
      short-id: "d667"
      spider-x: "/"

  - name: "芬兰01"
    type: vless
    server: nl.jiangniao.de
    port: 21445
    uuid: 75f436d9-b123-440a-b4b3-04d50490d05a
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "Vxx0cEAxavl5IB9mgdGybHWWFU5z5HUye2XR2UTkSgQ"
      short-id: "e2c1da25"
      spider-x: "/"

  - name: "乌克兰01"
    type: vless
    server: nl.jiangniao.de
    port: 29887
    uuid: 6ff59a2c-12f9-4929-b82e-b7a23b642e04
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "fxovmdbgZ2N6kxz47ciMu1AnEP0fK9UL7oy8RQ40eTE"
      short-id: "203e5451"
      spider-x: "/"

  - name: "新西兰01"
    type: vless
    server: rfc.jiangniao.de
    port: 16475
    uuid: 6cd6eb7c-f715-4c69-b9ec-5f3a46a275bf
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "4CeXM3VjkWtldeRvy23sPNTYseiCj8MmpSxwdETWPBQ"
      short-id: "af"
      spider-x: "/"

  - name: "吉尔吉斯坦01"
    type: vless
    server: nl.jiangniao.de
    port: 20021
    uuid: 7e2cb272-6ddb-49da-801a-4638cce2f5b9
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "szzXb530rQl16hT0dFVHQ184i5aRO5dTWPS8s_n9UQc"
      short-id: "48e2"
      spider-x: "/"

  - name: "冰岛01"
    type: vless
    server: snapstack.jiangniao.de
    port: 35631
    uuid: 341be18f-03dc-42ed-adcc-d688eb03c33b
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "P3OBzOmW6Y4euP8GsgN9vB_MnbU1s3784DcZIBAhwgI"
      short-id: "fbb6ad7db1b6e1"
      spider-x: "/"

  - name: "俄罗斯01"
    type: vless
    server: nl.jiangniao.de
    port: 32676
    uuid: e89ee658-9f02-40f8-a8de-80566fe340bc
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "Q6k0T38L0p6nfqWaLWU1qrsUYf5bJc-RmMaWDkvavx4"
      short-id: "dc"
      spider-x: "/"

  - name: "俄罗斯02"
    type: vless
    server: green.jiangniao.de
    port: 26571
    uuid: 9b4eaa0e-af08-4d9f-b2ed-7b6238776658
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "yahoo.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "tvUxHKatU4prIiyGUsqfSDd0I5Iwpe7w6UMul-yzCDo"
      short-id: "90"
      spider-x: "/"

  - name: "罗马尼亚01"
    type: vless
    server: nl.jiangniao.de
    port: 32043
    uuid: 985f9da8-5091-47ba-8bf1-bb33c9c0109c
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: "icloud.com"
    client-fingerprint: chrome
    reality-opts:
      public-key: "CRNmH2-XlYXqgH7ZnWGZ-Qv31H5CK8X3avTouTKBFGE"
      short-id: "f7171f"
      spider-x: "/"

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - DIRECT
      - "香港01"
      - "香港02"
      - "香港03"
      - "香港03（RFC）"
      - "香港04"
      - "香港05"
      - "香港X"
      - "日本01"
      - "日本02"
      - "日本03"
      - "日本04"
      - "日本05"
      - "新加坡01"
      - "美国01"
      - "美国02"
      - "美国03"
      - "印度01"
      - "新西兰01"
      - "美国家宽01"
      - "德国01"
      - "德国家宽01"
      - "英国01"
      - "芬兰01"
      - "乌克兰01"
      - "俄罗斯01"
      - "俄罗斯02"
      - "墨西哥01"
      - "墨西哥02"
      - "墨西哥03"
      - "墨西哥04"
      - "墨西哥05"
      - "墨西哥06"
      - "土耳其01"
      - "尼日利亚01"
      - "尼日利亚02"
      - "荷兰01"
      - "吉尔吉斯坦01"
      - "冰岛01"
      - "罗马尼亚01"

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
