mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

# —— 首包与并发优化 ——
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome

profile:
  store-selected: true   # 记住分组/节点选择

# —— 嗅探（Mihomo）——
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  force-domain:
    - +.netflix.com
    - +.youtube.com
    - +.googlevideo.com
  skip-domain:
    - +.local
    - +.lan

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  respect-rules: true

  # 启动用直连上游
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # 国内域名直连解析；境外域名经“DNS出口”解析（避免死锁）
  nameserver-policy:
    "geosite:cn":
      - 223.5.5.5
      - 119.29.29.29
    "geosite:geolocation-!cn":
      - https://1.1.1.1/dns-query#DNS出口
      - https://8.8.8.8/dns-query#DNS出口

  nameserver:
    - 223.5.5.5
    - 119.29.29.29

  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  fallback:
    - https://1.1.1.1/dns-query#DNS出口
    - https://8.8.8.8/dns-query#DNS出口
    - tls://1.1.1.1:853#DNS出口
    - tls://8.8.8.8:853#DNS出口

  fallback-filter:
    geoip: true
    geoip-code: CN
    ip-cidr:
      - 240.0.0.0/4

  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "localhost"
    - "connectivitycheck.gstatic.com"
    - "msftconnecttest.com"
    - "msftncsi.com"
    - "time.windows.com"
    - "time.apple.com"
    - "pool.ntp.org"
    - "ntp.ntsc.ac.cn"
    - "router.asus.com"
    - "miwifi.com"
    - "dns.alidns.com"
    - "resolver1.opendns.com"
    - "stun.l.google.com"
    - "download.windowsupdate.com"

# —— 节点（原样保留）——
proxies:
  - name: "美国01"
    type: vless
    server: jiangniao.jiangniao44.top
    port: 49545
    uuid: 8f7953fa-5ed6-4690-aaf1-f0c3da17d7a0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 4f-7xFlaZty0ZhYib5NHTvnxt22m7LaRUkSJbthWMAM
      short-id: "5247b7"

  - name: "美国02"
    type: vless
    server: jiang.jiangniao.de
    port: 32313
    uuid: 741278f0-e49c-4aa3-9f00-7933987534f0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: KL9NC2B3k5E7IfghGcA9ocF-7MdvuAgdPR7Zj4ljSlI
      short-id: 954ae509e86e10
      spider-x: /

  - name: "日本01"
    type: vless
    server: jiang1314.jiangniao44.top
    port: 32786
    uuid: 54e6dcc1-9e32-4147-81a0-6e70069a41ba
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 2LEyuwr6KgalqZfZsUjq1qQBPSSDPJdu6sOxFhrCaxw
      short-id: "ec2c02bced"

  - name: "新加坡01"
    type: vless
    server: sg01.jiangniao44.top
    port: 10719
    uuid: 93803b2d-661b-4442-be31-03eaa6f51fc1
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 8l_zz5Bdvpn1v6FuPIKxLz-dOyQH0ueT5YHUiU6MNQk
      short-id: "617f75a2"

  - name: "香港01"
    type: vless
    server: niao.jiangniao44.top
    port: 56079
    uuid: d2e6f717-0cdf-44f5-81e1-ad7f969ed903
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 8txY8epXE1T3O7H6-NVxleE_-J4dCVf4HSP6zdsx4TI
      short-id: "8332"

  - name: "土耳其01"
    type: vless
    server: jiang.jiangniao.de
    port: 27519
    uuid: 34c19ca4-2f3d-45e0-aa58-24846d80a7fe
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: kAx8PXXiu9rj_axNsOFT0XwKo2Wg4iaJcJ7AzhYOMyM
      short-id: "7388efc99b645c49"

  - name: "墨西哥01"
    type: vless
    server: jiang.jiangniao.de
    port: 28841
    uuid: 2bbdb4b6-2937-4279-ba24-5f0f3b51b77d
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: 4AJUyfD9YixhQn4B3c46VAYLC4LUuVc6twVm1yh78z4
      short-id: "73"

  - name: "墨西哥02"
    type: vless
    server: jiang.jiangniao.de
    port: 50682
    uuid: 41fe730f-127b-4c27-81ef-7e2a240b5e2e
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: zIIPhsd4pP9omVPxtUbusaJq9UcY7artFMY70MLQiWg
      short-id: "6f110ee0d9fd"

  - name: "墨西哥03"
    type: vless
    server: jiang.jiangniao.de
    port: 41236
    uuid: 1a16fad3-3182-445f-b27b-db018e4e5746
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: lDSUkgWuvxEQ1RzMbuwGCqdX7bn3uDetAYJmP4HGhXA
      short-id: "c5475819"
      spider-x: /

  - name: "尼日利亚01"
    type: vless
    server: jiang.jiangniao.de
    port: 19253
    uuid: fad9f8a7-13f3-4d42-823a-b7e9f6aff4f5
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: LKZqdbkcQcCmHqSOIlPA8_5sXuWs_GKJJt3S5WW5Jko
      short-id: "4a9c954f51a83119"
      spider-x: /

  - name: "美国家宽01"
    type: vless
    server: jiang.jiangniao.de
    port: 35111
    uuid: 2108bb8f-96e3-4cb6-885e-9c7e3d769f90
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: CwOikz2Soyfs5YVZBuDMdKRjZ7IfAPWQr_prrvh38DM
      short-id: "30e09630b2b7af"
      spider-x: /

  - name: "德国家宽01"
    type: vless
    server: jiang.jiangniao.de
    port: 54084
    uuid: 281c6b35-4633-4153-9c8b-581a7ad0ac69
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: b6EZJ9PO1Y3WGy3f88s1NZYfCOoaYuI62WrHqxjOqCI
      short-id: "ff5881b5"
      spider-x: /

  - name: "英国01"
    type: vless
    server: jiang.jiangniao.de
    port: 25071
    uuid: b08f446e-062f-41ec-8a1b-1498d23d1e48
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: B_Jriyd677O75kuZz2RsI-1pbVfqegTDKmYR7xDBpWE
      short-id: "ad"
      spider-x: /

proxy-groups:
  # 1) DNS 出口：避免启动死锁，默认 DIRECT
  - name: "DNS出口"
    type: select
    proxies:
      - DIRECT
      - "Auto"
      - "手选"

  # 2) 总开关：建议恒定选择 Auto
  - name: "Proxy"
    type: select
    proxies:
      - "Auto"
      - "手选"
      - DIRECT

  # 3) 自动测速（只放低延迟/家宽优质线路）
  - name: "Auto"
    type: url-test
    proxies:
      - "香港01"
      - "日本01"
      - "新加坡01"
      - "美国01"
      - "美国02"
      - "美国家宽01"
      - "德国家宽01"
      - "墨西哥03"
    url: https://cp.cloudflare.com/generate_204
    interval: 300
    tolerance: 50
    lazy: true
    timeout: 4000

  # 4) 手动选择（包含全部节点）
  - name: "手选"
    type: select
    proxies:
      - "香港01"
      - "日本01"
      - "新加坡01"
      - "美国01"
      - "美国02"
      - "美国家宽01"
      - "德国家宽01"
      - "墨西哥01"
      - "墨西哥02"
      - "墨西哥03"
      - "英国01"
      - "土耳其01"
      - "尼日利亚01"

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
