mixed-port: 7890
allow-lan: true
mode: Rule
log-level: info
external-controller: 127.0.0.1:9090

# ——首包与并发优化——
unified-delay: true
tcp-concurrent: true
global-client-fingerprint: chrome
profile:
  store-selected: true

# ——嗅探（Mihomo）——
sniffer:
  enable: true
  sniffing:
    - tls
    - http
  force-domain:
    - +.netflix.com
    - +.youtube.com
    - +.googlevideo.com
  skip-domain:
    - +.local
    - +.lan

dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:1053
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  use-hosts: true
  respect-rules: true

  # 冷启动用直连上游（快、避免环依赖）
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - 223.5.5.5
    - 119.29.29.29

  # 国外域名 → 经 Proxy 出站的 DoH
  nameserver-policy:
    "geosite:cn":
      - 223.5.5.5
      - 119.29.29.29
    "geosite:geolocation-!cn":
      - https://1.1.1.1/dns-query#Proxy
      - https://8.8.8.8/dns-query#Proxy

  fallback:
    - https://1.1.1.1/dns-query#Proxy
    - https://8.8.8.8/dns-query#Proxy
    - tls://1.1.1.1:853#Proxy
    - tls://8.8.8.8:853#Proxy
  fallback-filter:
    geoip: true
    geoip-code: CN
    ip-cidr:
      - 240.0.0.0/4

  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - "localhost"
    - "connectivitycheck.gstatic.com"
    - "msftconnecttest.com"
    - "msftncsi.com"
    - "time.windows.com"
    - "time.apple.com"
    - "pool.ntp.org"
    - "ntp.ntsc.ac.cn"
    - "router.asus.com"
    - "miwifi.com"
    - "dns.alidns.com"
    - "resolver1.opendns.com"
    - "stun.l.google.com"
    - "download.windowsupdate.com"

# ——节点列表（新增“俄罗斯02”）——
proxies:
  - name: "美国01"
    type: vless
    server: jiangniao.jiangniao44.top
    port: 49545
    uuid: 8f7953fa-5ed6-4690-aaf1-f0c3da17d7a0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "4f-7xFlaZty0ZhYib5NHTvnxt22m7LaRUkSJbthWMAM"
      short-id: "5247b7"

  - name: "美国02"
    type: vless
    server: jiang.jiangniao.de
    port: 32313
    uuid: 741278f0-e49c-4aa3-9f00-7933987534f0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "KL9NC2B3k5E7IfghGcA9ocF-7MdvuAgdPR7Zj4ljSlI"
      short-id: "954ae509e86e10"
      spider-x: /

  - name: "美国03"
    type: vless
    server: jiangniao.jiangniao44.top
    port: 30767
    uuid: 56cd42ef-83ac-49e1-81af-c20f89286fd0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "-iY2FuYNBLM7-_oJONO87TmupevVPls8VKSov3_vdhk"
      short-id: "072071"
      spider-x: /

  - name: "美国04"
    type: vless
    server: jiang.jiangniao.de
    port: 33901
    uuid: 6649a959-da30-46b6-a282-93f3cc91019a
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "7pEGJXrnTqrq4BvWCod1TLgCu99W1RENDrvinvdRaW4"
      short-id: "8a7cc0e4e9"
      spider-x: "/"

  - name: "日本01"
    type: vless
    server: jiang1314.jiangniao44.top
    port: 32786
    uuid: 54e6dcc1-9e32-4147-81a0-6e70069a41ba
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "2LEyuwr6KgalqZfZsUjq1qQBPSSDPJdu6sOxFhrCaxw"
      short-id: "ec2c02bced"

  - name: "日本02"
    type: vless
    server: rfc.jiangniao.de
    port: 42122
    uuid: 9e61d90e-c387-4b92-a6da-4c1b92027bd7
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "XdWaJDqRHBcPme2NXM_s6zKhvRuRaTjYw27gbFLCzW0"
      short-id: "3279de5b00f2"
      spider-x: /

  - name: "日本03"
    type: vless
    server: rfc.jiangniao.de
    port: 40669
    uuid: 8de8923b-85c0-4daa-a4a9-d2182295447e
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "Wg6dx0zz4jF_ZLL7dtbAf32J2l_3KXGeFtbkdC0VXyY"
      short-id: "9bf1a5d26dc0e2c4"
      spider-x: /
  
  - name: "日本04"
    type: vless
    server: green.jiangniao.de
    port: 51790
    uuid: 1b69afb7-9f0a-4e6c-9a4b-1fcf7621b0be
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "XJa0ZYOvtfwRz7aF8GprVrnEjc4S1rokGFhc-tI1YFk"
      short-id: "02c40852"
      spider-x: "/"
 
  - name: "新加坡01"
    type: vless
    server: rfc.jiangniao.de
    port: 57654
    uuid: 93b3ec8f-682f-46ae-a454-f0edc9d095e6
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "IyR-WPrH-SZXLx6K-8H6gYLXTxK1fObGNo8_c3fGoyA"
      short-id: "6afba8010f43"
      spider-x: /

  - name: "新加坡02"
    type: vless
    server: rfc.jiangniao.de
    port: 50821
    uuid: 6227227f-52ab-4695-8177-62855023cc70
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "fU7DWzwdZhRezE1rNnCLGQkvUjhrDKJ9fO9lTzf9MRs"
      short-id: "4a"
      spider-x: /

  - name: "台湾01"
    type: vless
    server: rfc.jiangniao.de
    port: 22625
    uuid: f79c11fb-ba1c-4c58-937a-02f00988313b
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "3z4OC_y8EeWEyCk1CNzoDT6rFkOAqBoTSwI7gq75KHI"
      short-id: "7fb499f7b3"
      spider-x: /

  - name: "台湾02"
    type: vless
    server: rfc.jiangniao.de
    port: 12205
    uuid: 19faee6a-47e9-4eab-991c-2bad3d663695
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "5zgaQVEXvj8gjiZlK6Sv9DT7MWgj9j9oxrrDbez1zVo"
      short-id: "c2"
      spider-x: /

  - name: "香港01"
    type: vless
    server: niao.jiangniao44.top
    port: 56079
    uuid: d2e6f717-0cdf-44f5-81e1-ad7f969ed903
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "8txY8epXE1T3O7H6-NVxleE_-J4dCVf4HSP6zdsx4TI"
      short-id: "8332"

  - name: "香港02"
    type: vless
    server: cnf.jiangniao.de
    port: 14339
    uuid: 305b46c8-62c5-4a5f-8eca-49696504b4c9
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "mFLxuM5neHOj_JiAaSXzKhQHNBjJOdMrcvi0nBZvoHg"
      short-id: "ff6c1c7939"
      spider-x: /

  - name: "香港03"
    type: vless
    server: rfc.jiangniao.de
    port: 14967
    uuid: 5f7e69bb-dd40-4b60-8984-5a1f1730091b
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "d1dzvm7d9JN2JunFIU0-cXH6ooS6VT-fUi_Z0G2Tfys"
      short-id: "ce9c32d59c9c8189"
      spider-x: /

  - name: "香港04"
    type: vless
    server: rfc.jiangniao.de
    port: 49624
    uuid: 6245f873-c14d-4cc9-895c-5e1816a8debb
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "qfH78UdGFMqCFfdPpHgHI5szzu2KXrVpxoyG12lZono"
      short-id: "a4"
      spider-x: /

  - name: "香港05"
    type: vless
    server: rfc.jiangniao.de
    port: 27277
    uuid: 4564fd83-b46f-4781-ba74-fd2b6a29875c
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "J2b48DFltcG4Eg4ZUlzoi76Mvx20U_kLhKnUyFZKXyA"
      short-id: "286927"
      spider-x: /

  - name: "香港X"
    type: vless
    server: rfc.jiangniao.de
    port: 47372
    uuid: 2f18157f-361e-4da9-a43d-abea314f82a8
    network: tcp
    tls: true
    udp: false
    flow: "xtls-rprx-vision"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "1OGj_Ab2uxPN0HMe29mgjuXeGJqqPZCuUSUWVU1h4mE"
      short-id: "a48c6562f9f96d35"
      spider-x: "/"

  - name: "印度01"
    type: vless
    server: rfc.jiangniao.de
    port: 16038
    uuid: ad898dc0-5173-4d84-a495-92adbee22bde
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "Wi_dye6vy6jr4iEBPHJKvBCf-bXflSlp_AI84tuQfzE"
      short-id: "7c485f0d"
      spider-x: /

  - name: "土耳其01"
    type: vless
    server: jiang.jiangniao.de
    port: 27519
    uuid: 34c19ca4-2f3d-45e0-aa58-24846d80a7fe
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "kAx8PXXiu9rj_axNsOFT0XwKo2Wg4iaJcJ7AzhYOMyM"
      short-id: "7388efc99b645c49"
      spider-x: /

  - name: "墨西哥01"
    type: vless
    server: jiang.jiangniao.de
    port: 42025
    uuid: bed8750e-36e0-425d-ae14-48d5b70cedd9
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "6baH2z3cSHXyNF-y60uOu15VRrHIA1s0w-c7DXvNLG4"
      short-id: "e5d928499470"
      spider-x: /

  - name: "墨西哥02"
    type: vless
    server: jiang.jiangniao.de
    port: 50682
    uuid: 41fe730f-127b-4c27-81ef-7e2a240b5e2e
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "zIIPhsd4pP9omVPxtUbusaJq9UcY7artFMY70MLQiWg"
      short-id: "6f110ee0d9fd"

  - name: "墨西哥03"
    type: vless
    server: jiang.jiangniao.de
    port: 41236
    uuid: 1a16fad3-3182-445f-b27b-db018e4e5746
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "lDSUkgWuvxEQ1RzMbuwGCqdX7bn3uDetAYJmP4HGhXA"
      short-id: "c5475819"
      spider-x: /

  - name: "墨西哥04"
    type: vless
    server: jiang.jiangniao.de
    port: 21699
    uuid: 6e822f5f-4d65-4d7a-ab9b-44b2286c205d
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "dDrx6x-HWghQs3x_s5bVW8VICdhhACVYTThlHScWlyI"
      short-id: "9d3ec8"
      spider-x: /

  - name: "尼日利亚01"
    type: vless
    server: jiang.jiangniao.de
    port: 19253
    uuid: fad9f8a7-13f3-4d42-823a-b7e9f6aff4f5
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "LKZqdbkcQcCmHqSOIlPA8_5sXuWs_GKJJt3S5WW5Jko"
      short-id: "4a9c954f51a83119"
      spider-x: /

  - name: "尼日利亚02"
    type: vless
    server: jiang.jiangniao.de
    port: 32506
    uuid: 49f43584-8742-43d0-9ea6-e38e0ce772b4
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "N2D2KLCsykq0fsUUwjrKvHdUo5b5SUfiLbXmSkJcfx8"
      short-id: "9acb194f8394a70c"
      spider-x: /

  - name: "尼日利亚03"
    type: vless
    server: snapstack.jiangniao.de
    port: 18928
    uuid: b374360e-f6d4-434a-a96d-1d3a4402b276
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "TlgOtcX5sZOF-42tBNSgsjInY99ptKI_nDcQLMTJaF8"
      short-id: "be"
      spider-x: "/"

  - name: "德国01"
    type: vless
    server: jiang.jiangniao.de
    port: 21361
    uuid: e8216fcb-2a03-4847-9290-eeb8790bc51f
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "gpOVDq28Vszg_aOf5TJl4eNwSwk_nQpDuJhq5MPJEX8"
      short-id: "12e0c546c0987b10"
      spider-x: /

  - name: "德国02"
    type: vless
    server: snapstack.jiangniao.de
    port: 11873
    uuid: 1d9dae7c-db5b-4d78-b4cc-2933459713cb
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "zz63GUGkBDMUvZNzEY6ugD6XYuNT0TIe-NefzNhqEhw"
      short-id: "e4"
      spider-x: "/"

  - name: "美国家宽01"
    type: vless
    server: jiang.jiangniao.de
    port: 35111
    uuid: 2108bb8f-96e3-4cb6-885e-9c7e3d769f90
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "CwOikz2Soyfs5YVZBuDMdKRjZ7IfAPWQr_prrvh38DM"
      short-id: "30e09630b2b7af"
      spider-x: /

  - name: "德国家宽01"
    type: vless
    server: jiang.jiangniao.de
    port: 54084
    uuid: 281c6b35-4633-4153-9c8b-581a7ad0ac69
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "b6EZJ9PO1Y3WGy3f88s1NZYfCOoaYuI62WrHqxjOqCI"
      short-id: "ff5881b5"
      spider-x: /

  - name: "英国01"
    type: vless
    server: jiang.jiangniao.de
    port: 25071
    uuid: b08f446e-062f-41ec-8a1b-1498d23d1e48
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "B_Jriyd677O75kuZz2RsI-1pbVfqegTDKmYR7xDBpWE"
      short-id: "ad"
      spider-x: /

  - name: "芬兰01"
    type: vless
    server: rfc.jiangniao.de
    port: 18782
    uuid: cb80c118-a2f9-47c8-9240-e9f84f0fb337
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "8azH5cnew4LV8UT_FY10GaH6yX4KqqlYZ4GPKtzD2Rg"
      short-id: "ba"
      spider-x: /

  - name: "乌克兰01"
    type: vless
    server: rfc.jiangniao.de
    port: 24590
    uuid: fc06fb02-ef7c-4608-a363-2d2314043bd0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "Tp7HWnEMbVR46uljXL7JnV_Iu9KRPByEvs5DcdenC2o"
      short-id: "48fbd12319"
      spider-x: /

  - name: "新西兰01"
    type: vless
    server: rfc.jiangniao.de
    port: 16475
    uuid: 6cd6eb7c-f715-4c69-b9ec-5f3a46a275bf
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "4CeXM3VjkWtldeRvy23sPNTYseiCj8MmpSxwdETWPBQ"
      short-id: "af"
      spider-x: /

  - name: "吉尔吉斯斯坦01"
    type: vless
    server: jiang1314.jiangniao44.top
    port: 19168
    uuid: 32cff7d0-8cc8-43fb-83c7-3f8db04d63c8
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "Jytt3P7bc6AQI1Swl9kGR1VejhmVQmepx1kU6OCafTk"
      short-id: "61"
      spider-x: "/"

  - name: "冰岛01"
    type: vless
    server: snapstack.jiangniao.de
    port: 35631
    uuid: 341be18f-03dc-42ed-adcc-d688eb03c33b
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "P3OBzOmW6Y4euP8GsgN9vB_MnbU1s3784DcZIBAhwgI"
      short-id: "fbb6ad7db1b6e1"
      spider-x: "/"

  - name: "俄罗斯01"
    type: vless
    server: rfc.jiangniao.de
    port: 22385
    uuid: 3b0958a8-b9bf-4a8b-b97d-19b993f66eb0
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: icloud.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "OUGQpGvMpViTmubP6jRqsgqJ-RJ_n-CEcc6zZI9JH1g"
      short-id: "797036"
      spider-x: "/"

  # ——新增：俄罗斯02——
  - name: "俄罗斯02"
    type: vless
    server: green.jiangniao.de
    port: 26571
    uuid: 9b4eaa0e-af08-4d9f-b2ed-7b6238776658
    network: tcp
    tls: true
    udp: true
    flow: "xtls-rprx-vision-udp443"
    servername: yahoo.com
    client-fingerprint: chrome
    reality-opts:
      public-key: "tvUxHKatU4prIiyGUsqfSDd0I5Iwpe7w6UMul-yzCDo"
      short-id: "90"
      spider-x: "/"

proxy-groups:
  - name: "Proxy"
    type: select
    proxies:
      - DIRECT
      - "香港01"
      - "香港02"
      - "香港03"
      - "香港04"
      - "香港05"
      - "香港X"
      - "日本01"
      - "日本02"
      - "日本03"
      - "日本04"
      - "新加坡01"
      - "新加坡02"
      - "台湾01"
      - "台湾02"
      - "美国01"
      - "美国02"
      - "美国03"
      - "美国04"
      - "印度01"
      - "新西兰01"
      - "美国家宽01"
      - "德国01"
      - "德国02"
      - "德国家宽01"
      - "英国01"
      - "芬兰01"
      - "乌克兰01"
      - "俄罗斯01"
      - "俄罗斯02"
      - "墨西哥01"
      - "墨西哥02"
      - "墨西哥03"
      - "墨西哥04"
      - "土耳其01"
      - "尼日利亚01"
      - "尼日利亚02"
      - "尼日利亚03"
      - "吉尔吉斯斯坦01"
      - "冰岛01"

rules:
  - DOMAIN-SUFFIX,local,DIRECT
  - DOMAIN-SUFFIX,lan,DIRECT
  - GEOSITE,CN,DIRECT
  - GEOIP,CN,DIRECT
  - MATCH,Proxy
